name: OneMonth Auth CD

on:
  workflow_dispatch: # 수동 실행
  workflow_run: # 특정 워크플로가 실행 완료되었을 때
    workflows: ["OneMonth Auth CI"] # CI 워크플로 이름
    types: [completed]

jobs:
  deploy:
    # CI 워크플로가 성공적으로 완료된 경우에만 실행
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PEM_KEY }}
          port: ${{ secrets.AWS_EC2_PORT }}
          script: |
            echo "Starting deployment..."

            # NVM 설정
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            echo "Navigating to project directory..."
            cd /home/ubuntu/HI_Auth

            echo "Switching to main branch and pulling latest code..."
            git switch main
            git pull origin main

            echo "Creating .env file..."
            echo "${{ secrets.ENV }}" > .env

            echo "Installing dependencies..."
            npm ci

            echo "Building application..."
            npm run build

            echo "Restarting server using PM2..."
            pm2 delete HI_AUTH || true
            pm2 --name HI_AUTH start dist/app.js
            pm2 save

            echo "Deployment completed successfully."
