name: OneMonth Auth CD

on:
  workflow_dispatch: # 수동 실행

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # .env 파일 생성
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV }}" > .env
          sed -i 's/ *= */=/g' .env # 공백 제거
          sed -i 's/^\"//g; s/\"$//g' .env # 따옴표 제거
          sed -i "s/'//g" .env # 작은따옴표 제거

      # Node.js 애플리케이션 빌드 및 실행
      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PEM_KEY }}
          port: ${{ secrets.AWS_EC2_PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            cd /home/ubuntu/HI_AUTH
            git switch main
            git pull origin main
            echo "${{ secrets.ENV }}" > .env
            sed -i 's/ *= */=/g' .env
            sed -i 's/^\"//g; s/\"$//g' .env
            sed -i "s/'//g" .env
            npm ci
            npm run build
            pm2 delete HI_AUTH || true
            pm2 --name HI_AUTH start dist/src/app.js
            pm2 save
