name: OneMonth Auth CI

on: # 언제 실행 될지 정의
  workflow_dispatch: # 수동 실행
  push: # PUSH 됐을 때
    branches: [main] # main 브랜치
  pull_request: # PR
    types: [opened, reopened, synchronize] # (생략가능)
    branches: [main] # main 브랜치

jobs:
  ci-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # ENV Secrets를 환경 변수로 설정
      - name: Export ENV variables
        run: |
          echo "${{ secrets.ENV }}" > .env
        shell: bash

      # 테스트 코드 실행
      - name: Run test
        run: |
          source .env
          npm run test
