name: OneMonth Auth CI

on: # 언제 실행될지 정의
  workflow_dispatch: # 수동 실행
  push: # PUSH 됐을 때
    branches: [main] # main 브랜치
  pull_request: # PR
    types: [opened, reopened, synchronize] # PR 이벤트
    branches: [main] # main 브랜치 #테스트용으로 dev로변경

jobs:
  ci-test:
    runs-on: ubuntu-24.04

    steps:
      # 1. 소스 코드 가져오기
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Node.js 환경 설정
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4. 환경 변수 설정
      - name: Create and load .env file
        run: |
          echo "${{ secrets.ENV }}" > .env
          sed -i 's/ *= */=/g' .env # 공백 제거
          sed -i 's/^\"//g; s/\"$//g' .env # 따옴표 제거
          sed -i "s/'//g" .env # 작은따옴표 제거
          cat .env # 디버깅용으로 생성된 .env 파일 출력

      # 5. 테스트 코드 실행
      - name: Run tests
        run: npm run test
